### ISSUE TITLE
老哥，没有数据库的数据，请问能分享下吗？

### ISSUE THREAD

**Issue by Yesterdaylove** [Eric54920/Blog#23]
OperationalError at /
no such table: web_article

**Comment by Eric54920** [comment]
你们有迁移数据库嘛，迁移了之后就有这个表呀

**Comment by Yesterdaylove** [comment]
老哥，我先新建了local_settings.py 然后填写了
DATABASES = {
        'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'blog_db',
        'HOST': '127.0.0.1',
        'PORT': 3306,
        'USER': 'root',
        'PASSWORD': '145236'
    }
}
然后我运行了    
python manage.py makemigrations
python manage.py migrate
然后数据库显示如下，好像没有这个表，我不清楚是哪个配置我写错了吗
![image](https://github.com/Eric54920/Blog/assets/63202524/08add969-84a0-416c-ae31-4f57dc63a05f)

**Comment by Eric54920** [comment]
你看看你的web目录下是不是没有migrations这个包，这个要手动创建一个，不然检测不到models。

迁移完成之后要插入的数据你执行以下代码，生成一个密码，修改密码功能我在开发
```python
import hashlib

SECRET_KEY = '+%@zdh)6xuv^)&&@781zx9))9+pwo1lw%c@@in^yd2kl$t&rn*'

def sha256(string):
    """ MD5加密 """
    hash_object = hashlib.sha256(SECRET_KEY.encode('utf-8'))
    hash_object.update(string.encode('utf-8'))
    return hash_object.hexdigest()


print(sha256("你的密码"))
```

**Comment by Yesterdaylove** [comment]
我试了好像怎么都创建不了migrations包，老哥你说的在web下建migrations是指创建一个文件夹吗？
我看其他博客说是运行python manage.py makemigrations的时候会自动创建一个migration包吗
![image](https://github.com/Eric54920/Blog/assets/63202524/395b67cd-0d4a-470e-b2fc-8801ab434b1d)

**Comment by Eric54920** [comment]
就是在web目录下创建一个`migrations`文件夹，里面再创建一个名为`__init__.py`的文件，之前的版本是可以自己创建的，这个版本不会自己创建，先手动加一下吧

**Comment by Yesterdaylove** [comment]
可以了，多谢老哥

**Comment by Eric54920** [comment]
嗯，好的

**Comment by Yesterdaylove** [comment]
![image](https://github.com/Eric54920/Blog/assets/63202524/5047a057-7daf-4b3f-bdd2-8cf7c28f57bd)
h好像管理员页面进不去

**Comment by Eric54920** [comment]
你的sql中密码得要你自己生成，用上面我发的那段脚本，你这个密码没有加密

**Comment by Yesterdaylove** [comment]
![image](https://github.com/Eric54920/Blog/assets/63202524/7e18b954-61ab-4fbd-8f8e-153ea2f682b7)
好的，我使用了加密后的密码，insert到表里后，然后登录的时候用的未加密密码，但是报错显示是用户不存在，也没登录进去

**Comment by Eric54920** [comment]
那不应该呀。你调用sha256方法了嘛，或者你的密码是什么，我给你生成，对比一下

**Comment by Yesterdaylove** [comment]
+%@zdh)6xuv^)&&@781zx9))9+pwo1lw%c@@in^yd2kl$t&rn*
我看显示是用户名不存在，是和密码有关吗

**Comment by Eric54920** [comment]
是的，密码不对就会提醒用户不存在

**Comment by Eric54920** [comment]
你把`+%@zdh)6xuv^)&&@781zx9))9+pwo1lw%c@@in^yd2kl$t&rn*`这个加密了嘛，那加密后应该是`d04f048ce3c11a18de2b6d77c93776bc9349b28feebd9f86b62aac63e9dd4d70`，你改个能记住的密码吧，这个太难记了

**Comment by Yesterdaylove** [comment]
![image](https://github.com/Eric54920/Blog/assets/63202524/bb258007-da1f-4022-83bf-0e1eb49eb71a)

**Comment by Yesterdaylove** [comment]
老哥，这个加密我运行出来好像和你不一样，现在我用你的那个加密成功登进去了

**Comment by Eric54920** [comment]
你有没有把`你的密码`替换掉呀，你的替换成你的，比如：xxxxxxx

**Comment by Yesterdaylove** [comment]
![image](https://github.com/Eric54920/Blog/assets/63202524/b751b48a-1f19-483a-99b6-e6dade8918bf)
老哥，这个啥问题，要修改什么地方吗

**Comment by Yesterdaylove** [comment]
管理员登录进来就是这个报错
![image](https://github.com/Eric54920/Blog/assets/63202524/fe2873a8-b70a-4515-a24e-3d8ae838449a)

**Comment by Eric54920** [comment]
这个问题我昨天修复了，你拉一下最新的代码
