### ISSUE TITLE
老哥，我好像没有看到delete_file这个函数，现在针对相册进行删除时出现了报错

### ISSUE THREAD

**Issue by Yesterdaylove** [Eric54920/Blog#24]
![image](https://github.com/Eric54920/Blog/assets/63202524/33f3075b-ab11-498f-a363-943c34e42303)

![image](https://github.com/Eric54920/Blog/assets/63202524/bfa9c088-0653-4e47-9b16-9e243a3371e2)

**Comment by Eric54920** [comment]
拉一下最新代码

**Comment by Yesterdaylove** [comment]
ok了
